### ISSUE TITLE
Unable to build with `Mediator` installed

### ISSUE THREAD

**Issue by MitchellW-DWL** [martinothamar/Mediator#104]
Ive installed the nuget library and checked the csproj is correct, but just getting the following:
![image](https://github.com/martinothamar/Mediator/assets/111871510/7d736207-8681-4db9-af71-c53042ad510b)

**Comment by MitchellW-DWL** [comment]
```
  MediatorGenerator got unknown error while generating mediator implementation, please report this to the issue tracker on github at https://github.com/martinothamar/Mediator/issues/new . Error: Index was outside the bounds of the array.:    at Mediator.SourceGenerator.CompilationAnalyzer.Initialize() in /_/src/Mediator.SourceGenerator.Implementation/Analysis/CompilationAnalyzer.cs:line 136
```
👀

**Comment by martinothamar** [comment]
Do you have a repro for this? [The samples](https://github.com/martinothamar/Mediator/tree/release/v2.1/samples) are building fine in any version I know of, do you install the Mediator packages in the same way?

**Comment by MitchellW-DWL** [comment]
> Do you have a repro for this?
Afraid I can't share - I was trying to migrate project away from MediatR to use this package, I've installed both the SourceGenerator and Abstractions libraries and that was as far as it got?

**Comment by MitchellW-DWL** [comment]
Just had another bash at this and was able to get it all building ok - must've been messing something stupid up; thanks though 👍
