### ISSUE TITLE
dotnet build inside docker throws error "does not contain a definition for 'AddMediator'"

### ISSUE THREAD

**Issue by illunix** [martinothamar/Mediator#107]
I try to build my docker image and I get 
error CS1061: 'IServiceCollection' does not contain a definition for 'AddMediator' and no accessible extension method 'AddMediator' accepting a first argument of type 'IServiceCollection'

When i build my app outside docker everything works, can someone help me resolve this issue?

I use dockerfile generated by vs

**Comment by Genmutant** [comment]
I have the same problem. Here a minimal example to reproduce: https://github.com/Genmutant/AddMediatorTest_20230914

Output from dotnet build --no-restore
`MSBuild version 1[7](https://github.com/Genmutant/AddMediatorTest_20230914/actions/runs/6184739479/job/16788959095#step:5:8).8.0-preview-23418-03+0125fc9fb for .NET
/usr/share/dotnet/sdk/8.0.100-rc.1.23455.8/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/home/runner/work/AddMediatorTest_20230914/AddMediatorTest_20230914/AddMediatorTest/AddMediatorTest.csproj]
CSC : warning CS[8](https://github.com/Genmutant/AddMediatorTest_20230914/actions/runs/6184739479/job/16788959095#step:5:9)784: Generator 'IncrementalMediatorGenerator' failed to initialize. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentNullException' with message 'Value cannot be null. (Parameter 'path1')' [/home/runner/work/AddMediatorTest_20230[9](https://github.com/Genmutant/AddMediatorTest_20230914/actions/runs/6184739479/job/16788959095#step:5:10)14/AddMediatorTest_20230914/AddMediatorTest/AddMediatorTest.csproj]
Error: /home/runner/work/AddMediatorTest_20230914/AddMediatorTest_20230914/AddMediatorTest/Program.cs(4,[10](https://github.com/Genmutant/AddMediatorTest_20230914/actions/runs/6184739479/job/16788959095#step:5:11)): error CS1061: 'ServiceCollection' does not contain a definition for 'AddMediator' and no accessible extension method 'AddMediator' accepting a first argument of type 'ServiceCollection' could be found (are you missing a using directive or an assembly reference?) [/home/runner/work/AddMediatorTest_202309[14](https://github.com/Genmutant/AddMediatorTest_20230914/actions/runs/6184739479/job/16788959095#step:5:15)/AddMediatorTest_20230914/AddMediatorTest/AddMediatorTest.csproj]

Build FAILED.

CSC : warning CS8784: Generator 'IncrementalMediatorGenerator' failed to initialize. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentNullException' with message 'Value cannot be null. (Parameter 'path1')' [/home/runner/work/AddMediatorTest_20230914/AddMediatorTest_20230914/AddMediatorTest/AddMediatorTest.csproj]
Error: /home/runner/work/AddMediatorTest_20230914/AddMediatorTest_20230914/AddMediatorTest/Program.cs(4,10): error CS1061: 'ServiceCollection' does not contain a definition for 'AddMediator' and no accessible extension method 'AddMediator' accepting a first argument of type 'ServiceCollection' could be found (are you missing a using directive or an assembly reference?) [/home/runner/work/AddMediatorTest_20230914/AddMediatorTest_20230914/AddMediatorTest/AddMediatorTest.csproj]
    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.55
Error: Process completed with exit code 1.`

**Comment by illunix** [comment]
Alright, then I will use .NET 7, thanks

**Comment by martinothamar** [comment]
I think I managed to fix this, could you try [2.1.6](https://www.nuget.org/packages/Mediator.SourceGenerator/2.1.6) or [3.0.0-preview.10](https://www.nuget.org/packages/Mediator.SourceGenerator/3.0.0-preview.10) please?

**Comment by Genmutant** [comment]
Works great, thanks for the fast fix. Did you find the root source of the problem? I couldn't find anything fitting in the [breaking changes](https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0), though I might have overlooked it.

**Comment by martinothamar** [comment]
I didn't dig much into it to be honest, was mostly concerned about blocked users. But I assume the issue was that `Assembly.GetExecutingAssembly().Location` now returns null. I'm not sure why, and I didn't find any clues in the breaking changes either. Luckily this codepath wasn't used at all (maybe it was at some point)
