### ISSUE TITLE
.NET 8 RC1 CSC: Error CS8784 : Generator 'IncrementalMediatorGenerator' failed to initialize

### ISSUE THREAD

**Issue by credfeto** [martinothamar/Mediator#108]
```
18>CSC: Error CS8784 : Generator 'IncrementalMediatorGenerator' failed to initialize. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentNullException' with message 'Value cannot be null. (Parameter 'path1')'
```

Haven't been able to work out what the argument null is.  With a source generator I wrote it was due to accessing Assembly.Location to get path to read the assembly file version, but not sure if it is this in this case.

note when building with the latest .net 7 is ok

**Comment by pascallapradepodform3d** [comment]
For information, we saw this too today in our project, after switching to .NET 8 RC1. We were using .NET 8 previews so far, and did not encounter the issue.

If we pin the `8.0.100-preview.7.23376.3` SDK version in a `global.json`, our project builds correctly.

As soon as we pin the `8.0.100-rc.1.23455.8` SDK version, then we see the issue above.

**Comment by martinothamar** [comment]
yeah looks like this is the same issue as: https://github.com/martinothamar/Mediator/issues/107

I'll take some time to debug later tonight

**Comment by martinothamar** [comment]
I think I managed to fix this, could you try [2.1.6](https://www.nuget.org/packages/Mediator.SourceGenerator/2.1.6) or [3.0.0-preview.10](https://www.nuget.org/packages/Mediator.SourceGenerator/3.0.0-preview.10) please?

**Comment by pascallapradepodform3d** [comment]
Worked for me, thanks so much :) !

**Comment by credfeto** [comment]
Confirmed; 2.1.6 has worked for me too.  Many thanks for the quick response & fix.
