### ISSUE TITLE
Usage without dependency injection

### ISSUE THREAD

**Issue by nathanpovo** [martinothamar/Mediator#117]
I am interested in using this package. However, the environment that I am trying to use it in is somewhere without dependency injection.

Is it possible to use this package without dependency injection? The docs and samples do not offer any info on how this can be done.

**Comment by nathanpovo** [comment]
This might also be useful in solving #10

**Comment by martinothamar** [comment]
Sorry, thats not really possible since `Microsoft.Extensions.DependencyInjection` is used throughout all the code
