### ISSUE TITLE
Sample projects don't work in isolation

### ISSUE THREAD

**Issue by matthewblott** [martinothamar/Mediator#133]
I thought this might be related to #94 but it seems the sample projects don't work by themselves. For example the ASPNET_Core_Indirect project runs fine when I build the Mediator solution but if I separate the three ASPNET_Core_Indirect projects then the handlers aren't registered. Here's a screenshot of my setup, I haven't made any changes at all:

![Screenshot 2023-12-09 at 22 23 42](https://github.com/martinothamar/Mediator/assets/1231417/4e3e632a-7ccb-41be-a768-8e5073675b95)

Here's the output when running a curl request in the terminal:

![Screenshot 2023-12-09 at 22 31 04](https://github.com/martinothamar/Mediator/assets/1231417/6251c97a-f8db-4698-b29e-9cb38118e84d)

It's because the handlers haven't been generated. This is what I would expect to see in the `GetWeatherForecastHandler` class and is what I get when I run the samples as part of the Mediator solution:

![Screenshot 2023-12-09 at 22 33 34](https://github.com/martinothamar/Mediator/assets/1231417/1bd57382-1510-4668-81fa-2f714dce4069)

But this is what I see instead (no references appear):

![Screenshot 2023-12-09 at 22 35 59](https://github.com/martinothamar/Mediator/assets/1231417/91506328-b416-46ed-bcbe-cc469fc44862)

Any help appreciated :-)

**Comment by matthewblott** [comment]
I'm going to close this. I'm trying out the version 3.0 preview release and it appears I can get it to work. I'll post back with an update but I don't want to keep a ticket open if it isn't worth fixing :-)

**Comment by martinothamar** [comment]
This is kind of unexpected for me... I will look into this and the linked issue. There's nothing in the main branch that should affect this

**Comment by matthewblott** [comment]
I have an example of a multi project solution with version 3.0 and .NET 8 [here](https://github.com/matthewblott/northwind-aspnet-hotwire). I have it working for my purposes now. Thanks all the same :-)

**Comment by Trigun27** [comment]
Sadly but i have similar mistake.
