### ISSUE TITLE
[Question] How to automatically register xxxHandlers<,> ?

### ISSUE THREAD

**Issue by jeffward01** [martinothamar/Mediator#16]
Hello all!

I have spent some time on this, and stumped.  Is there a way to automatically register handlers? Specifically `ICommandHandler<,>`?  I saw some links here:

* https://event-driven.io/en/how_to_register_all_mediatr_handlers_by_convention/ 
* https://github.com/khellang/Scrutor/issues/96 

And I have also tried on my own using [Scrutor](https://github.com/khellang/Scrutor) and can't seem to find a solution.

Does anyone know of a solution?

**Comment by martinothamar** [comment]
Command handlers should be automatically added to DI container. It is documented but probably not well enough: https://github.com/martinothamar/Mediator#3-usage-and-abstractions

> Standard message handlers are automatically picked up and added to the DI container in the generated AddMediator method. Pipeline behaviors need to be added manually.

You can actually see the generated code for it like this if using VS:
![image](https://user-images.githubusercontent.com/5425986/156229898-14dba730-e236-4987-a751-ee3cd6e21cdf.png)

`Mediator.g.cs` contains the `AddMediator` method where all handlers are registered.

**Comment by jeffward01** [comment]
Thank you for your library again and prompt response!!

I saw that it is documented, but I noticed it was only documented for `IQueryHandler` and not `ICommandHandler`. Also when I tried this and it did not work for me, I will take some screenshots and make a sample and show. Please give me a few hours or day or two.  

Thank you again for this excellent library!  I am sure it is some issue on my end <3

**Comment by Zsolt-Bendes** [comment]
I can confirm that the `ICommandHandler` s are not invoked. I tried with latest stable and latest preview version. In both version the commands are not working IF there is a command specific pipeline registered. 

To reproduce:

1.  Create and register a command specific pipeline
2. Create a command and send the command request.

Expected behavior: The command is invoked, and the pipeline runs.

Observed behavior: The command is not invoked

**Comment by Zsolt-Bendes** [comment]
I have a bit more information. Looks like on my side the DI in the pipeline could not be resolved and swallowed the exception(?).
@jeffward01 maybe look around in your DI setup

**Comment by jeffward01** [comment]
@Zsolt-Bendes @martinothamar - After testing, I can confirm that it **does** work for me.  If I have my setup like this:

![image](https://user-images.githubusercontent.com/12589359/157130845-7f31b72e-9a07-4d3b-ae5d-45debdf05a58.png)

It works for me with success for `ICommandHandler`

Its strange, because when I opened this ticket, I swear it did not work and I debugged it. This must be what @Zsolt-Bendes is experiencing.  I am not sure what I did to 'fix' this. The error occurred in a separate solution to the one I am referencing here.

--

I think we can decide that this is perhaps 'intermittent'?

**Comment by jeffward01** [comment]
@martinothamar - One thing i'd like to mention, please let me know if I should open another ticket for this.

In my screenshot:
![image](https://user-images.githubusercontent.com/12589359/157131078-131f68c5-ed51-4ee8-b60c-c46e4dd5ed28.png)

Often `AddMediator();` shows an error that it cannot be found, however the code **does compile fine without error.**.  The error will show on my 'Error List' at the bottom of visual studio, but it compiles fine. This leads me to believe its some sort of Analyzer setting which is set to _Show as Error_. 

@Zsolt-Bendes @martinothamar - do you also experience this red underlining?

----

I have a setting where If not file-scoped namespace, show error:

![image](https://user-images.githubusercontent.com/12589359/157131319-db33d4a3-4d38-4d84-844a-65323df29a99.png)


Then it will show this, and an error. When I compile it compiles 100% fine with success.  Perhaps its the same thing?

**Comment by Zsolt-Bendes** [comment]
> do you also experience this red underlining?
yes, I do. I just ignore it. Does not break my workflow.

**Comment by martinothamar** [comment]
@Zsolt-Bendes hey, sorry I took so long but I've written a test for this now and cant quite reproduce. This test is green: https://github.com/martinothamar/Mediator/pull/18/commits/d26053c5fd0c5177daf56faf0edd738ea663c6b7

This matches your error report as far as I can see. Can you spot any difference from your own case?

**Comment by martinothamar** [comment]
Looks like it was fixed in 17.1 actually, I've been on 17.0 for a while so hadn't noticed: https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes#issues-addressed-in-171

**Comment by jeffward01** [comment]
Thanks for this! @martinothamar  - Sorry for the long reply! Its all working now! WooHoo!
