### ISSUE TITLE
Help in diagnosing MessageHandler not being called

### ISSUE THREAD

**Issue by CheloXL** [martinothamar/Mediator#20]
Hi,
I have a solution where I have a business project (where commands, queries and messages exist, Mediator.Abstractions linked), and an api project (where I have Mediator linked).

Commands/queries are working perfect. but not messages. Message handlers are not being called and I don't have any clues about why.

Is there any place where the source generator puts the generated files, so I can check if at least there are any information about my handlers? Or, is there any way I can diagnose this?

Thanks in advance.

**Comment by martinothamar** [comment]
See the attached screenshot, you can see the generated code in Visual Studio. I recommend use of the later versions of Visual Studio 2022 as there has been some good improvements in terms of source generators lately.

![image](https://user-images.githubusercontent.com/5425986/162291511-214c0b28-ae1a-43b9-adc7-a454def5c99c.png)

Do you have some sample code I can look at? Are you talking about pipeline behaviors? In that case there is some sample code you can look at that might help you: https://github.com/martinothamar/Mediator/blob/f32f1ed89f7460ce31b3df6d10b463e4242658ec/samples/SimpleConsole/Program.cs

**Comment by CheloXL** [comment]
Ok, found the issue. I was using the method `Publish<>`, but I was obtaining the message from a list of `<INotification>`, so the DI was never picking up the handler. Had to cast each entry as `(object)` so the code now correctly calls `Publish(object)` instead of `Publish<INotification>(INotification)`.

Thanks anyways for taking your time to answer.

**Comment by martinothamar** [comment]
Ahh, thanks for reporting this 👍  I've fixed the generic publish method so that it can do the casting for us as well. It's part of the 2.0 preview (along with some other upcoming changes)
![image](https://user-images.githubusercontent.com/5425986/162595460-8c95b8f7-268d-4667-b9fa-11a5d5f21b8a.png)

**Comment by CheloXL** [comment]
Ah, excelent... thank you for this great project!
