### ISSUE TITLE
Corrupt state of HashSet in Mediator.SourceGenerator.CompilationAnalyzer causing high CPU in Visual Studio

### ISSUE THREAD

**Issue by AlexDelepine** [martinothamar/Mediator#55]
**Description**

I am from the Visual Studio performance team and our telemetry has shown that there are high amounts of CPU being consumed by the callstack I pasted below. It appears that either there are multiple threads writing to the HashSet at the same time, or a thread reading from it while another thread is writing to it. HashSet is not inherently thread-safe, so this concurrent access to the HashSet is causing it to enter a corrupted state and the threads essentially get stuck in an infinite loop. This causes multiple threads to get stuck inside of HashSet.AddIfNotPresent and each thread to indefinitely consume a full core of CPU within Visual Studio.

**CallStack**

+microsoft.codeanalysis!Microsoft.CodeAnalysis.UserFunctionExtensions+<>c__DisplayClass3_0\`2[Microsoft.CodeAnalysis.SourceProductionContext,System.ValueTuple\`2[System.__Canon,System.Collections.Immutable.ImmutableArray\`1[System.__Canon]]].<WrapUserAction>b__0(!0,!1,valueclassSystem.Threading.CancellationToken)
+mediator.sourcegenerator.roslyn40!Mediator.SourceGenerator.IncrementalMediatorGenerator.<Initialize>b__5_3(valueclassMicrosoft.CodeAnalysis.SourceProductionContext,valueclassSystem.ValueTuple\`2>)
+mediator.sourcegenerator.roslyn40!IncrementalMediatorGenerator.ExecuteInternal
+mediator.sourcegenerator.implementation!CompilationAnalyzer.Analyze
+mediator.sourcegenerator.implementation!CompilationAnalyzer.PopulateMetadata
+mediator.sourcegenerator.implementation!Mediator.SourceGenerator.CompilationAnalyzer.<PopulateMetadata>g__ProcessMember|97_0(classSystem.Collections.Generic.Queue\`1,classMicrosoft.CodeAnalysis.INamespaceOrTypeSymbol,classSystem.Collections.Generic.Dictionary\`2)
+mediator.sourcegenerator.implementation!Mediator.SourceGenerator.CompilationAnalyzer.<PopulateMetadata>g__ProcessInterface|97_1(int32,classMicrosoft.CodeAnalysis.INamedTypeSymbol,classMicrosoft.CodeAnalysis.INamedTypeSymbol,bool,classSystem.Collections.Generic.Dictionary\`2)
+system.core.ni!System.Collections.Generic.HashSet`1[System.__Canon].AddIfNotPresent(System.__Canon)

**Solution**

Ensuring reads/writes to this HashSet are thread-safe will fix this issue. You can likely either use a lock to prevent concurrent access or use a thread-safe data structure such as ConcurrentBag instead of HashSet.

**Comment by martinothamar** [comment]
Hi, thanks for bringing this up! Our team has actually seen this but by the time I was ready to dump the process and inspect I couldn't reproduce anymore, so my assumption was that some behavior changed across VS versions leading to this bug not being produced anymore. Do you see this in your telemetry? Does this CPU usage spread across all VS versions or only specific ones? 

I'll definitely make CompilationAnalyzer threadsafe. Thanks!

**Comment by AlexDelepine** [comment]
Thanks for looking into this! I do see in telemetry that this seems to be affecting all VS versions (including latest release).
It's difficult to manually repro this type of bug because it requires multiple threads to access the HashSet at the exact same time and for the HashSet to do something internally (such as resize) for it to get in this corrupted state, so it's hard to predictably make this reoccur in testing conditions (although with enough operations it statistically should reoccur eventually).

**Comment by martinothamar** [comment]
I found a race condition that would lead to the issue you describe. It's been fixed in the linked PR and released to the newest preleases: 2.1.0-preview.2 and 2.0.28-rc

The RC branch will become 2.0 final release in a day or two, just have some things to finish up. 
Thanks again for reporting this, helped a ton 🥇
