### ISSUE TITLE
Question, when to use message types?

### ISSUE THREAD

**Issue by mxmissile** [martinothamar/Mediator#59]
Not really an issue with Mediator, more of me just not understanding how it works. Message types are [explained here](https://github.com/martinothamar/Mediator#31-message-types), but why would you use certain types over others? For example:

`IRequest<out TResponse>` vs `ICommand<out TResponse>` Why would I use one over the other?

`ICommand` vs `IRequest` vs `INotification`? Same question here. The descriptions tell me they all do the same thing.

**Comment by martinothamar** [comment]
It's mostly this part:

> As you can see, you can achieve the exact same thing with requests, commands and queries. But I find the distinction in naming useful if you for example use the CQRS pattern or for some reason have a preference on naming in your application.

So it's up to the developer - for example one thing I have done in a project using CQRS is to define a `CachedQuery` base type with a corresponding `CachedQueryPipelineBehavior` which uses `Microsoft.Extensions.Caching` library to cache results and return early in the pipeline. So any query I want to be cached in the API will just derive from `CachedQuery`. This functionality makes sense for queries but not for commands in the way we use them. So thats the intention and its not obvious, so I could probably improve the documentation and maybe also provide an example where the distinction is useful.

**Comment by mxmissile** [comment]
Thank you! I missed that part, but there it is!

**Comment by mkgn** [comment]
@martinothamar Can you add an example of your caching pipeline code to the document please?

**Comment by martinothamar** [comment]
Sure, I could maybe include it in a sample
