### ISSUE TITLE
what is default ServiceLifetime if I have not specified anything in AddMediator()

### ISSUE THREAD

**Issue by krishrana17** [martinothamar/Mediator#63]
What If I have not specified anything  in AddMediator() method then what should be the default ServiceLifetime? Is it Transient? What should be the best ServiceLifetime for Web Application?

**Comment by martinothamar** [comment]
The default is Singleton, which makes it conservative/lightweight by default. There is no universal answer here I think. If I can get away with it I tend to stick to singleton services in general and write stateless code (most services naturally are in web applications). I haven't really seen many good usecases for transient registration personally, and it allocates a lot for usually no reason. Scoped can be useful for ASP.NET Core request scoped services and things of that nature, but it's really up to the developer what is wanted/needed.

**Comment by xavierjohn** [comment]
@martinothamar Please add more thoughts/documentation on when we should used scoped.

Your one .net core web sample has singleton
https://github.com/martinothamar/Mediator/blob/main/samples/apps/ASPNET_Core/Program.cs#L11

while the other has scoped.
https://github.com/martinothamar/Mediator/blob/main/samples/apps/ASPNET_Core_CleanArchitecture/AspNetCoreSample.Application/ServiceCollectionExtensions.cs#L12

The problem I am specifically trying to solve is, using clean architecture, what if the App layer and ACL is shared between a web job and API.  Background jobs in Web Job needs singleton. Should I move the registration of Mediator to Program.cs so that API is scoped while WebJob is Singleton? That implies that Mediator registration cannot happen at the Application layer.

**Comment by martinothamar** [comment]
I don't think there is anything specific to this library in regards to choosing lifetime, all depends on what you want for the application. These days I tend to not use scoped at all if I can, and so the code is designed around that fact. I think if I were you I would either make the job execute code in scopes or the API run singleton - which to choose would depend on the complexity realistically, but I again would favor singleton 😄

**Comment by xavierjohn** [comment]
Let's assume there is a scenario where ApplicationLayer needs to be shared between the API layer and a Web job. In API layer, DB context needs to be scoped but in WebJob it needs to be a singleton. 
It is possible to pass the lifetime as a parameter to the .AddApplication(lifecycle) but how do we tell the mediator source code generator to use Scoped for the API project and Singleton for the Webjob project?  My guess is, I will have to move the AddMediator to the exe project like the API or webjob and it can no longer be in the Application assembly. Maybe this mix and match is not even allowed.

**Comment by martinothamar** [comment]
No I think you need to use the same lifetime in both projects (e.g. make the webjob scoped as well by making sure executions create a DI scope). I assume you are referencing EFCore here which doesn't really force you to do scoped either, you can use the context factory as well which is singleton. The lifetime for Mediator needs to be a compiletime constant, so it can't be dynamic like that

**Comment by xavierjohn** [comment]
If I add Mediator in the Program.cs of the web API as scoped and as a singleton in the Program.cs of the web job, would that work? Is code generation only in the project where the generator is added, which in this case will be the API and the web job executable.
I am not using EF Core; I just want to understand where I need to be cautious when using Mediator.

**Comment by martinothamar** [comment]
> Is code generation only in the project where the generator is added

Yes, that is correct, so if you call `AddMediator` in the executable projects then you should be fine (assuming the application layer code tolerates both lifetimes)

**Comment by xavierjohn** [comment]
Here is what I am planning to do, let me know if you see any issues.
1) All the commands and handles will remain in the application layer.
2) The functions like AddPresentation(), AddAntiCorruptionLayer(), etc will remain in their respective assemblies but will take a lifetime parameter. AddMediator() alone will be pulled out into the exe layer.

With this setup, I should be able to have scoped scope in API layer and Singleton in Webjobs, at the same time I don't need to repeat all the DI Adds in each exe, except for AddMediator().
