### ISSUE TITLE
Why it's not supporting .net 7?

### ISSUE THREAD

**Issue by stormaref** [martinothamar/Mediator#68]
I'm using this package in .net 7 and the service collection extension is not available I cannot register the mediator service nor change it's lifetime

**Comment by martinothamar** [comment]
It does support .NET 7.0. See the example here
![image](https://user-images.githubusercontent.com/5425986/208240285-70861a23-2b59-4ac8-8bd0-77d3ed28df07.png)

Do you have some more information/a repro? If something does go wrong during build, you should see errors in the build output.

**Comment by stormaref** [comment]
It was Rider problem :)
