### ISSUE TITLE
Request handlers not disposed when using transient lifetime

### ISSUE THREAD

**Issue by glen-84** [martinothamar/Mediator#69]
```cs
builder.Services.AddMediator(options => options.ServiceLifetime = ServiceLifetime.Transient);
```

If you implement `IDisposable` or `IAsyncDisposable`, the handler is not disposed.

Switching back to MediatR and it works correctly.

**Comment by martinothamar** [comment]
Thanks for reporting, will fix this and publish as part of 3.0 preview release. Will comment here when that is done
