### ISSUE TITLE
Error on EF Core Update method after using Mediator

### ISSUE THREAD

**Issue by mou7866** [martinothamar/Mediator#70]
Hi,

Great improvement with Mediator, we have changed over from MediatR recently. However I am getting an error on the EF Core Update method after the update to Mediator and I wanted to check if this is known or if I can get any help solving this issue. 

For DI of Mediator:

`Services.AddMediator(options =>
            {
                options.Namespace = DomainName;
                options.ServiceLifetime = ServiceLifetime.Transient;
            });`

All my other services are also Transient. 

However, when calling the EF Core Update method to update a record in the database, I get the error below:

`The instance of entity type 'Entity' cannot be tracked because another instance with the key value '{Id: 6629b094-1884-4e5d-8d03-ae2dfd5472a5}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.\r\n `

The Add and Find Methods from EF Core are working fine.

I am using version 6.0.10 of the EF Core Nuget Package and using version 2.0.29 of Mediator.

If more info is required, please let me know and I will provide it. I have tried changing the other Lifetimes as well to see if that solves the issue but I still get the same error.

Thank you for the help

**Comment by martinothamar** [comment]
Hi! I'm not sure how this can be related to Mediator itself, are you sure there were no other changes that could interfere? Would you be able to reproduce this in a sample? If not I can try so myself whenever I have time.

There was [this bug](https://github.com/martinothamar/Mediator/issues/69) reported where transient handlers aren't being disposed, not sure if that can be related? Apart from this I've not yet heard of any relevant functional changes from the MediatR API.

Do you have some sample code for how you are doing the updates? Is it read-modify-write or something else? And which database?

**Comment by mou7866** [comment]
@martinothamar thank you for the response. 

Yes, the bug is related I think because when we create a new Scope in each Handler like the below, it works fine. For some reason, even on 2 separate endpoints, the resources injected into Handlers and Services are not disposed. 

`public async ValueTask<TResponse> Handle(TRequest request, CancellationToken cancellationToken)
        {
            using IServiceScope scope = ServiceScopeFactory.CreateScope();
            return await HandleRequest(scope, request, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }`

When I do the update of the database record when creating a separate scope for each scope like the above, it works fine. 

Looking forward to the fix in version 3.

**Comment by martinothamar** [comment]
As mentioned on the other issue, decided to push a fix to [2.0.30](https://www.nuget.org/packages/Mediator.Abstractions/2.0.30) along with an explanation on what caused it
