### ISSUE TITLE
Warning message: "...conflicts with the imported type 'MediatorOptions'..."

### ISSUE THREAD

**Issue by ladislav-filip** [martinothamar/Mediator#71]
Hi,
When I compile, I get the above warning.
Why is this message displayed?

Thanx

```
  The type 'MediatorOptions' in 'Mediator.SourceGenerator.Roslyn40\Mediator.SourceGenerator.IncrementalMediatorGenerator\MediatorOptions.g.cs' 
  conflicts with the imported type 'MediatorOptions' in 'Transportation.Logic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. 
  Using the type defined in 'Mediator.SourceGenerator.Roslyn40\Mediator.SourceGenerator.IncrementalMediatorGenerator\MediatorOptions.g.cs'.
```

**Comment by martinothamar** [comment]
Do you have your own type called MediatorOptions? Or do you have multiple projects referencing the source generator package? The source generator package generates the options class.

**Comment by ladislav-filip** [comment]
I have three projects in a solution.
'Mediator.SourceGenerator' was in two projects, I removed it from the library project and left it in the main project. Now is build without warnings.
Is it good stretegy?

Thanx

**Comment by martinothamar** [comment]
Yes, that is the intention, the sourcegenerator package should be referenced once in the outermost package, typically where the DI container i constructed. The sourcegenerator package generates and registers the mediator implementation, so there should be only 1 per DI container. The places where you want to define requests, commands, queries etc you only need the abstractions package. I can probably document this better
