### ISSUE TITLE
MessagePreProcessor not found

### ISSUE THREAD

**Issue by StormrageSTR** [martinothamar/Mediator#81]
I trying to migrate my old application from MediatR to this Mediator. So I got issue with  MessagePreProcessor which I want to use instead of IRequestPreProcessor.
It looks like it doesn't exist. I've included Mediator.Abstractions and Mediator.SourceGenerator both version 2.0.30 and can't use it
![image_2023-02-08_14-58-46](https://user-images.githubusercontent.com/37656837/217501574-cc6ea203-f61d-4c4e-90c2-e8c5b32ff18b.png)

**Comment by martinothamar** [comment]
These types are in the 2.1 preview currently. So they will be available there 🙂

**Comment by martinothamar** [comment]
Closing this for now, but feel free to comment if there's anything else
