### ISSUE TITLE
Question: IAsyncEnumerable`1 Handlers

### ISSUE THREAD

**Issue by TorreyGarland** [martinothamar/Mediator#9]
Are there any plans to implement handlers that return an instance of IAsyncEnumerable`1?

**Comment by martinothamar** [comment]
Haven't though about it yet, but that would be cool. Will look into it next time I'm working on this 👍

**Comment by martinothamar** [comment]
FYI support for IAsyncEnumerable`1 was released in v1.0.* just now

**Comment by TorreyGarland** [comment]
just wanted to say thank you for your hard work. 

Cheers!!!
