### ISSUE TITLE
EntryPointNotFoundException throwns in ValueTask

### ISSUE THREAD

**Issue by CheloXL** [martinothamar/Mediator#90]
I'm crossposting this issue on [aspnetcore](https://github.com/dotnet/runtime/issues/85990), because the error is thrown on the ValueTask returned by Mediator.

I'm not sure where the error is. Not sure if Mediator is generating something wrong between the Send and the handler, or if this is a framework issue.

Maybe you can take a look too?

**Comment by halter73** [comment]
It looks like the following code is actually unsafe:

https://github.com/martinothamar/Mediator/blob/7955fc8ca5247fdf98f2265337885c70e72b13a0/src/Mediator.SourceGenerator.Implementation/resources/Mediator.sbn-cs#L399

See https://github.com/dotnet/runtime/issues/85990#issuecomment-1540764556

**Comment by martinothamar** [comment]
Thanks for the report! and yes this is 100% a Mediator bug. That is indeed not safe when using a base-type as the type argument. Will look into this (and the linked PR), probably next week as I'm going away for a couple of days

**Comment by martinothamar** [comment]
#92 is looking pretty good, so as soon as the requested changes are committed it will be merged and released in a 2.1 patch.

**Comment by martinothamar** [comment]
The bugfix from #92 is available in [2.1.5](https://www.nuget.org/packages/Mediator.SourceGenerator/2.1.5)
