### ISSUE TITLE
VS 2022 features crashing using Mediator.Abstraction

### ISSUE THREAD

**Issue by ShadyHarbinger** [martinothamar/Mediator#96]
If I reference projects which references other projects using Mediator.Abstractions Visual Studio starts crashing in the project that references the other one.

For example if I have the reference chain:
**X.API** (WEB project using Mediator.SourceGenerator package) --> **X.Application**.
**X.Application** (library) --> **X.Infrastructure**.
**X.Infrastructure** (library) --> **X.Domain**.
**X.Domain** (library) --> X.Common (Library using Mediator.Abstractions package).

VS starts throwing exceptions in the **X.API** project:
![image](https://github.com/martinothamar/Mediator/assets/77984125/a27ac069-4ac2-4664-a166-a5870f2cb814)

All got the same exception: _StreamJsonRpc.RemoteInvocationException: SyntaxTree is not part of the compilation (Parameter 'syntaxTree'_

**Comment by martinothamar** [comment]
Should be fixed in the latest versions, see #93
